# Generated by Django 2.2.8 on 2019-12-10 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('figura', models.ImageField(upload_to='')),
                ('autor', models.CharField(default='Anonymous', max_length=30)),
                ('documento', models.FileField(upload_to='documents/')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('descricao', models.TextField(default='4Linux Django')),
            ],
        ),
    ]
